#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.JQuery.Datatables.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\DataTable.cshtml"
    using Mvc.JQuery.Datatables;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DataTable.cshtml")]
    public class DataTable : System.Web.Mvc.WebViewPage<DataTableVm>
    {
        public DataTable()
        {
        }
        public override void Execute()
        {


WriteLiteral("<table id=\"");


            
            #line 3 "..\..\Views\Shared\DataTable.cshtml"
      Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"display\" >\r\n    <thead>\r\n        <tr>\r\n");


            
            #line 6 "..\..\Views\Shared\DataTable.cshtml"
             foreach (var column in Model.Columns)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>");


            
            #line 8 "..\..\Views\Shared\DataTable.cshtml"
               Write(column);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 9 "..\..\Views\Shared\DataTable.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n        <tr>\r\n");


            
            #line 12 "..\..\Views\Shared\DataTable.cshtml"
             foreach (var column in Model.Columns)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>");


            
            #line 14 "..\..\Views\Shared\DataTable.cshtml"
               Write(column);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 15 "..\..\Views\Shared\DataTable.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=""5"" class=""dataTables_empty"">
                Loading data from server
            </td>
        </tr>
    </tbody>
</table>
<script type=""text/javascript"">
    $(document).ready(function () {
        var $table = $('#");


            
            #line 28 "..\..\Views\Shared\DataTable.cshtml"
                    Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        var dt = $table.dataTable({\r\n            \"bProcessing\": true,\r\n     " +
"       \"bStateSave\": true,\r\n            \"bServerSide\": true,\r\n            \"sAjax" +
"Source\": \"");


            
            #line 33 "..\..\Views\Shared\DataTable.cshtml"
                       Write(Html.Raw(Model.AjaxUrl));

            
            #line default
            #line hidden
WriteLiteral(@""",
            ""fnServerData"": function (sSource, aoData, fnCallback) {
                $.ajax({
                    ""dataType"": 'json',
                    ""type"": ""POST"",
                    ""url"": sSource,
                    ""data"": aoData,
                    ""success"": fnCallback
                });
            }
        });
        dt.columnFilter({ sPlaceHolder: ""head:before"" });
    });
</script>
");


        }
    }
}
#pragma warning restore 1591
