#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.JQuery.Datatables.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\DataTable.cshtml"
    using Mvc.JQuery.Datatables;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DataTable.cshtml")]
    public class DataTable : System.Web.Mvc.WebViewPage<DataTableVm>
    {
        public DataTable()
        {
        }
        public override void Execute()
        {


WriteLiteral("<table id=\"");


            
            #line 3 "..\..\Views\Shared\DataTable.cshtml"
      Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"display\" >\r\n   <thead>\r\n\t\t<tr>\r\n");


            
            #line 6 "..\..\Views\Shared\DataTable.cshtml"
             foreach (var column in Model.Columns)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>");


            
            #line 8 "..\..\Views\Shared\DataTable.cshtml"
               Write(column);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 9 "..\..\Views\Shared\DataTable.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"dataTables_empty\"" +
">Loading data from server</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n<script type=\"text" +
"/javascript\">\r\n    $(document).ready(function () {\r\n        $(\'#");


            
            #line 20 "..\..\Views\Shared\DataTable.cshtml"
       Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\').dataTable({\r\n            \"bProcessing\": true,\r\n            \"bServerSide\": true" +
",\r\n            \"sAjaxSource\": \"");


            
            #line 23 "..\..\Views\Shared\DataTable.cshtml"
                       Write(Model.AjaxUrl);

            
            #line default
            #line hidden
WriteLiteral(@""",
            ""fnServerData"": function (sSource, aoData, fnCallback) {
                $.ajax({
                    ""dataType"": 'json',
                    ""type"": ""POST"",
                    ""url"": sSource,
                    ""data"": aoData,
                    ""success"": fnCallback
                });
            }
        });
    });
</script>

");


        }
    }
}
#pragma warning restore 1591
